modulo03-python-web-com-django/20240309_aula03/enquetes/urls.py
from django.urls import path

from . import views

app_name = "enquetes"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pergunta_id>/", views.detalhe, name="detalhe"),
    path("<int:pergunta_id>/resultados", views.resultados, name="resultados"),
    path("<int:pergunta_id>/votar", views.votar, name="votar")
]

modulo03-python-web-com-django/20240309_aula03/estatisticas/urls.py
from django.urls import path

from . import views

app_name = "estatisticas"

urlpatterns = [
    path("", views.index, name="index"),
]

modulo03-python-web-com-django/20240309_aula03/site_pessoal/urls.py
from django.contrib import admin
from django.urls import path, include

from enquetes import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("__debug__/", include("debug_toolbar.urls")),

    path('enquetes/', include('enquetes.urls')),
    path('estatisticas/', include('estatisticas.urls')),
]

modulo03-python-web-com-django/20240309_aula03/enquetes/models.py
from django.contrib.auth.models import User, AnonymousUser
from django.db import models

class Pergunta(models.Model):
    texto = models.CharField(max_length=200)
    data_de_publicacao = models.DateTimeField("Data de publicação")

    def __str__(self):
        return self.texto

    class Meta:
        db_table = "tb_perguntas"


class Opcao(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=100)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.texto} ({self.pergunta.texto})"

    class Meta:
        db_table = "tb_opcoes"


class OpiniaoPergunta(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    nota = models.IntegerField()
    comentario = models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.pergunta.texto} ({self.nota})"
    
    class Meta:
        db_table = "tb_opinioes_perguntas"

modulo03-python-web-com-django/20240309_aula03/enquetes/views.py
# A classe HttpResponse é utilizada quando queremos retornar uma resposta HTTP válida
from django.http import HttpRequest

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from enquetes.models import Pergunta, Opcao, OpiniaoPergunta

"""
As funções criadas dentro do módulo views, devem ser consideradas views que serão ligadas a uma url, criando uma rota
"""

# Obrigatoriamente, todas as funções view devem receber o parâmetro request, mesmo se esse parâmetro não for utilizado
def index(request):
    
    perguntas = Pergunta.objects.order_by('-data_de_publicacao')
    contexto = {
        "perguntas": perguntas
    }

    # Utilizamos a função render para renderizar os templates como respostas HTTP
    return render(
        request,                # O argumento request é obrigatório
        "enquetes/index.html",  # O caminho completo até o template
        context=contexto        # O parâmetro opcional context. Indica as variáveis de contexto que serão passadas para o template
    )
    
def detalhe(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)

    return render(
        request,
        "enquetes/detalhe.html",
        {"pergunta": pergunta}
    )

def resultados(request: HttpRequest, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)

    if request.method == "GET":

        ja_avaliou = pergunta.opiniaopergunta_set.filter(usuario=request.user).exists()

        return render(
            request,
            "enquetes/resultados.html",
            {
                "pergunta": pergunta,
                "ja_avaliou": ja_avaliou
            }
        )
    
    elif request.method == "POST":
        nota_pergunta = request.POST.get("nota_pergunta")
        comentario_pergunta = request.POST.get("comentario_pergunta")

        opiniao_pergunta = OpiniaoPergunta(
            pergunta=pergunta,
            usuario=request.user,
            nota=int(nota_pergunta),
            comentario=comentario_pergunta
        )

        opiniao_pergunta.save()

        return redirect("enquetes:index")

def votar(request, pergunta_id):
    
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)

    try:
        opcao_escolhida = pergunta.opcao_set.get(pk=request.POST["opcao"])
        
    except (KeyError, Opcao.DoesNotExist):
        return render(
            request,
            "enquetes/detalhe.html",
            {
                "mensagem_erro": "Você não escolheu uma opção.",
                "pergunta": pergunta
            }
        )
    
    else:
        opcao_escolhida.votos += 1
        opcao_escolhida.save()

        return redirect(
            reverse("enquetes:resultados", args=(pergunta.id,))
        )

modulo03-python-web-com-django/20240309_aula03/estatisticas/views.py
from django.db.models import Count, Sum, Avg
from django.shortcuts import render

from enquetes.models import Pergunta, Opcao

def index(request):

    quantidade_perguntas_cadastradas = Pergunta.objects.count()
    quantidade_opcoes_cadastradas = Opcao.objects.count()
    lista_perguntas_ordenada_quantidade_votos = Pergunta.objects.annotate(
        num_votos=Sum("opcao__votos")
    ).order_by('-num_votos')[:10]
    media_opcoes_por_pergunta = Pergunta.objects.annotate(
        num_opcoes=Count('opcao')
    ).aggregate(media_opcoes=Avg("num_opcoes"))

    contexto = {
        "quantidade_perguntas_cadastradas": quantidade_perguntas_cadastradas,
        "quantidade_opcoes_cadastradas": quantidade_opcoes_cadastradas,
        "lista_perguntas_ordenada_quantidade_votos": lista_perguntas_ordenada_quantidade_votos,
        "media_opcoes_por_pergunta": media_opcoes_por_pergunta["media_opcoes"]
    }

    return render(
        request,
        "estatisticas/index.html",
        context=contexto
    )

modulo03-python-web-com-django/20240309_aula03/enquetes/templates/enquetes/detalhe.html
{% extends "base.html" %}

{% block conteudo %}
    <form action="{% url 'enquetes:votar' pergunta.id %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ pergunta.texto }}</h1></legend>
            {% if mensagem_erro %}
                <p><strong>{{ mensagem_erro }}</strong></p>
            {% endif %}

            {% for opcao in pergunta.opcao_set.all %}
                <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}">
                <label for="opcao{{ forloop.counter }}">{{ opcao.texto }}</label>
            {% endfor %}
        </fieldset>
        <br>
        <input type="submit" value="Votar">
    </form>
{% endblock conteudo %}

modulo03-python-web-com-django/20240309_aula03/enquetes/templates/enquetes/index.html
{% extends "base.html" %}

{% block conteudo %}
    {% comment %} perguntas é a variável de contexto passada na função render do arquivo views.py {% endcomment %}
    {% if perguntas %}
    {% comment %}Quando precisamos utilizar um comando (if, for, etc), utilizamos chaves e porcentagem{% endcomment %}
        <ul>
            {% for pergunta in perguntas %}
                {% comment "" %}Quando queremos mostrar o valor de uma variável, utilizamos chaves duplas{% endcomment %}
                <li><a href="{% url 'enquetes:detalhe' pergunta.id %}">{{ pergunta.texto }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Não foram encontradas perguntas cadastradas.</h2>
    {% endif %}
    <hr>
    <a href="{% url "estatisticas:index" %}">Visualizar estatísticas do site</a>
{% endblock conteudo %}

modulo03-python-web-com-django/20240309_aula03/enquetes/templates/enquetes/resultados.html
{% extends "base.html" %}

{% block conteudo %}
    <h1>{{ pergunta.texto }}</h1>
    <hr>

    <ul>
        {% for opcao in pergunta.opcao_set.all %}
            <li>{{ opcao.texto }} -- {{ opcao.votos }} voto{{ opcao.votos|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'enquetes:detalhe' pergunta.id %}">Votar novamente</a>
    <br><br><hr>

    <h2>Avalie essa enquete</h2>

    {% if user.is_authenticated %}
        {% if ja_avaliou %}
            <p>Você já avaliou essa pergunta</p>
        {% else %}
        <form action="#" method="post">
            {% csrf_token %}
            <select name="nota_pergunta" id="nota_pergunta">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5" selected>5</option>
            </select>
            <label for="nota_pergunta">Escolha a nota</label>
            <br><br>
            <label for="comentario_pergunta">Escreva um comentário (opcional)</label><br>
            <textarea name="comentario_pergunta" id="comentario_pergunta" cols="50" rows="5"></textarea><br>
            <input type="submit" value="Enviar">
        </form>
        <hr>
        {% endif %}
    {% else %}
        <p>Você precisa estar autenticado para avaliar a enquete.</p>
    {% endif %}

    <h2>Comentários dessa enquete</h2>
    <ul>
        {% for opiniao_pergunta in pergunta.opiniaopergunta_set.all %}
            <li>
                {{ opiniao_pergunta.comentario|default:"<i>Comentário vazio </i>" }}.
                ({{ opiniao_pergunta.nota }})
                -- {{ opiniao_pergunta.usuario.username|default:"<i>Anônimo</i>" }}
            </li>
        {% endfor %}
    </ul>
{% endblock conteudo %}

modulo03-python-web-com-django/20240309_aula03/estatisticas/templates/estatisticas/index.html
{% extends "base.html" %}

{% block conteudo %}
    <h1>Estatísticas</h1>

    <h4>Quantidade de perguntas cadastradas: {{ quantidade_perguntas_cadastradas|default:"Sem informação" }}</h4>
    <h4>Quantidade de opções cadastradas: {{ quantidade_opcoes_cadastradas|default:"Sem informação" }}</h4>
    <h4>Lista com as 10 perguntas com mais votos: </h4>
    <ul>
        {% for pergunta in lista_perguntas_ordenada_quantidade_votos %}
            <li>{{ pergunta }} - {{ pergunta.num_votos }} voto{{ pergunta.num_votos|pluralize }}</li>
        {% endfor %}
    </ul>
    <h4>Quantidade média de opções por pergunta: {{ media_opcoes_por_pergunta|default:"Sem informação"|floatformat:2 }}</h4>

    <hr>
    <a href="{% url "enquetes:index" %}">Voltar para as enquetes</a>
{% endblock conteudo %}

modulo03-python-web-com-django/20240309_aula03/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block titulo %}<title>Sistema de enquetes</title>{% endblock titulo %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block extra_css %}{% endblock extra_css %}
</head>
  <body>
    <div class="container">
      {% block conteudo %}{% endblock conteudo %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>