modulo03-python-web-com-django/20240427_aula10/gerenciamento_kitnets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('gestao/', include('gestao.urls')),
    path('registro/', include('registro.urls')),

    path('__debug__/', include('debug_toolbar.urls'))
]

modulo03-python-web-com-django/20240427_aula10/gestao/urls.py
from django.urls import path

from . import views

app_name = "gestao"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "meu-perfil/",
        views.meu_perfil,
        name="meu_perfil"
    ),
    path(
        "nao-autorizado/",
        views.nao_autorizado,
        name="nao_autorizado"
    ),
    path(
        "alugar-imovel/",
        views.lista_imoveis,
        name="lista_imoveis"
    ),
    path(
        "imoveis/<imovel_id>/",
        views.detalhe_imovel,
        name="detalhe_imovel"
    ),
    path(
        "imoveis/<imovel_id>/alugar/",
        views.alugar_imovel,
        name="alugar_imovel"
    )
]

modulo03-python-web-com-django/20240427_aula10/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block titulo_pagina %}Gestão de Kitnets{% endblock titulo_pagina %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        {% block navbar %}
          {% if user.is_authenticated %}
            {% include "navbar.html" %}  
          {% endif %}
        {% endblock navbar %}

        {% block conteudo %}{% endblock conteudo %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block extra_javascript %}{% endblock extra_javascript %}
  </body>
</html>

modulo03-python-web-com-django/20240427_aula10/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "gestao:index" %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'gestao:lista_imoveis' %}">Alugar Imóvel</a>
          </li>
          <li class="nav-item">
            <a class="nav-link{% if perms.registro.perfil_bloqueado %} disabled{% endif %}" href="{% url "gestao:meu_perfil" %}">Perfil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sair</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>