modulo03-python-web-com-django/20240427_aula10/gerenciamento_kitnets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('gestao/', include('gestao.urls')),
    path('registro/', include('registro.urls')),

    path('__debug__/', include('debug_toolbar.urls'))
]

modulo03-python-web-com-django/20240427_aula10/gestao/urls.py
from django.urls import path

from . import views

app_name = "gestao"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "meu-perfil/",
        views.meu_perfil,
        name="meu_perfil"
    ),
    path(
        "nao-autorizado/",
        views.nao_autorizado,
        name="nao_autorizado"
    ),
    path(
        "alugar-imovel/",
        views.lista_imoveis,
        name="lista_imoveis"
    ),
    path(
        "imoveis/<imovel_id>/",
        views.detalhe_imovel,
        name="detalhe_imovel"
    ),
    path(
        "imoveis/<imovel_id>/alugar/",
        views.alugar_imovel,
        name="alugar_imovel"
    )
]

modulo03-python-web-com-django/20240427_aula10/gestao/models.py
import uuid

from django.db import models

from registro.models import Perfil

class Imovel(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    tipo_logradouro = models.CharField(max_length=20)
    logradouro = models.CharField(max_length=200)
    numero = models.CharField(max_length=20)
    complemento = models.CharField(max_length=20)
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=2)
    descricao = models.TextField(null=True, blank=True)
    disponivel = models.BooleanField(default=True)

    def __str__(self) -> str:
        return "{} localizada em {}-{}".format(
            self.descricao,
            self.cidade,
            self.estado
        )
    
    class Meta:
        db_table = "tb_imoveis"


class TipoContrato(models.Model):

    tipo_contrato = models.CharField(max_length=20)
    descricao = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self) -> str:
        return "{} ({})".format(
            self.tipo_contrato.title(),
            self.descricao
        )

    class Meta:
        db_table = "tb_tipos_contrato"


class Contrato(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    tipo_contrato = models.ForeignKey(
        TipoContrato, null=True, on_delete=models.SET_NULL
    )

    locatario = models.ForeignKey(
        Perfil, null=True, on_delete=models.SET_NULL
    )

    imovel = models.ForeignKey(
        Imovel, null=True, on_delete=models.SET_NULL
    )

    data_de_inicio = models.DateField()
    data_de_fim = models.DateField()
    esta_ativo = models.BooleanField(default=True)
    valor_total = models.FloatField()
    valor_parcela = models.FloatField()
    observacoes = models.TextField(blank=True, null=True)

    class Meta:
        db_table = "tb_contratos"

class InformacaoAluguelTipoContratoImovel(models.Model):
    
    imovel = models.ForeignKey(
        Imovel,
        null=True,
        on_delete=models.SET_NULL
    )
    tipo_contrato = models.ForeignKey(
        TipoContrato,
        null=True,
        on_delete=models.SET_NULL
    )
    valor = models.FloatField()
    observacoes = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return "Contrato {} para o imóvel '{}'. Valor: R$ {:.2f}".format(
            self.tipo_contrato.tipo_contrato,
            self.imovel,
            self.valor
        )

    class Meta:
        db_table = "informacoes_aluguel_tipo_contrato_imovel"

class Parcelamento(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    contrato = models.ForeignKey(
        Contrato,
        null=True,
        on_delete=models.SET_NULL
    )
    numero_parcela = models.IntegerField()
    valor_parcela = models.FloatField()
    data_vencimento = models.DateField()
    paga = models.BooleanField(default=False)
    data_pagamento = models.DateField(null=True, blank=True)

    class Meta:
        db_table = "tb_parcelamentos"

modulo03-python-web-com-django/20240427_aula10/gestao/views.py
from datetime import datetime, timedelta

from django.contrib.auth.decorators import (
    login_required,
    permission_required
)
from django.http import HttpRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from gestao.models import Contrato, Imovel, Parcelamento, TipoContrato
from registro.models import Perfil

def index(request):
    return render(
        request,
        "gestao/index.html"
    )

@login_required
def meu_perfil(request: HttpRequest):

    if request.user.has_perm("registro.perfil_bloqueado"):
        return render(
            request,
            "gestao/nao_autorizado.html"
        )

    if request.method == "GET":

        atualizado_com_sucesso = int(request.GET.get("atualizado_com_sucesso", "0"))

        return render(
            request,
            "gestao/meu_perfil.html",
            {"atualizado_com_sucesso": bool(atualizado_com_sucesso)}
        )
    
    if request.method == "POST":
        usuario = request.user

        nome = request.POST.get("nome")
        sobrenome = request.POST.get("sobrenome")
        email = request.POST.get("email")
        documento = request.POST.get("documento")
        genero = request.POST.get("genero")
        data_de_nascimento = request.POST.get("data_de_nascimento")

        usuario.first_name = nome
        usuario.last_name = sobrenome
        usuario.email = email

        perfil_usuario = Perfil.objects.get(pk=usuario.id)
        
        perfil_usuario.documento = documento
        perfil_usuario.genero = genero

        data_de_nascimento = datetime.strptime(
            data_de_nascimento, "%Y-%m-%d"
        ).date()

        perfil_usuario.data_de_nascimento = data_de_nascimento

        usuario.save()
        perfil_usuario.save()
        
        return redirect(
            f"{reverse('gestao:meu_perfil')}?atualizado_com_sucesso=1"
        )
    
@login_required
def nao_autorizado(request: HttpRequest):
    return render(
        request,
        "gestao/nao_autorizado.html"
    )

@login_required
def lista_imoveis(request: HttpRequest):

    lista_imoveis = Imovel.objects.filter(disponivel=True)
    imoveis = []

    for imovel in lista_imoveis:

        imovel_id = imovel.id
        descricao = imovel.descricao
        preco_diaria = imovel.informacaoalugueltipocontratoimovel_set.filter(tipo_contrato=1).first()
        preco_mensal = imovel.informacaoalugueltipocontratoimovel_set.filter(tipo_contrato=2).first()

        dados_imovel = {
            "id": imovel_id,
            "descricao": descricao,
            "preco_diaria": None if not preco_diaria else preco_diaria.valor,
            "preco_mensal": None if not preco_mensal else preco_mensal.valor
        }

        imoveis.append(dados_imovel)
    
    return render(
        request,
        "gestao/lista_imoveis.html",
        {
            "imoveis": imoveis
        }
    )

@login_required
def detalhe_imovel(request: HttpRequest, imovel_id: str):

    imovel = get_object_or_404(Imovel, pk=imovel_id)

    preco_diaria = imovel.informacaoalugueltipocontratoimovel_set.get(tipo_contrato=1)
    preco_mensal = imovel.informacaoalugueltipocontratoimovel_set.get(tipo_contrato=2)

    return render(
        request,
        "gestao/detalhe_imovel.html",
        {
            "imovel": imovel,
            "preco_diaria": None if not preco_diaria else preco_diaria.valor,
            "preco_mensal": None if not preco_mensal else preco_mensal.valor
        }
    )

@login_required
def alugar_imovel(request: HttpRequest, imovel_id: str):


    if request.method == "GET":
        imovel = get_object_or_404(Imovel, pk=imovel_id)

        preco_diaria = imovel.informacaoalugueltipocontratoimovel_set.get(tipo_contrato=1)
        preco_mensal = imovel.informacaoalugueltipocontratoimovel_set.get(tipo_contrato=2)

        return render(
            request,
            "gestao/alugar_imovel.html",
            {
                "imovel": imovel,
                "preco_diaria": None if not preco_diaria else preco_diaria.valor,
                "preco_mensal": None if not preco_mensal else preco_mensal.valor
            }
        )
    else:
        tipo_contrato = get_object_or_404(
            TipoContrato,
            pk=int(request.POST.get("tipo_contrato"))
        )
        periodo = int(request.POST.get("periodo"))

        imovel = get_object_or_404(Imovel, pk=request.POST.get("imovel_id"))

        data_de_inicio = timezone.now().date()

        if tipo_contrato.id == 1:
            valor_parcela = imovel.informacaoalugueltipocontratoimovel_set.get(tipo_contrato=1).valor
            valor_total = periodo * valor_parcela
            data_de_fim = data_de_inicio + timedelta(days=periodo)

        elif tipo_contrato.id == 2:
            valor_parcela = imovel.informacaoalugueltipocontratoimovel_set.get(tipo_contrato=2).valor
            valor_total = periodo * valor_parcela
            data_de_fim = data_de_inicio + timedelta(days=periodo*30)

        contrato = Contrato(
            tipo_contrato=tipo_contrato,
            locatario=request.user.perfil,
            imovel=imovel,
            data_de_inicio=data_de_inicio,
            data_de_fim=data_de_fim,
            esta_ativo=True,
            valor_total = valor_total,
            valor_parcela=valor_parcela
        ).save()

        imovel.disponivel = False
        imovel.save()

        if tipo_contrato.id == 1:
            parcelamento = Parcelamento(
                numero_parcela=1,
                valor_parcela=valor_total,
                data_vencimento=timezone.now().date() + timedelta(days=1),
                contrato=contrato
            )

            parcelamento.save()

        elif tipo_contrato.id == 2:
            for index in range(1, periodo+1):
                parcelamento = Parcelamento(
                numero_parcela=index,
                valor_parcela=valor_parcela,
                data_vencimento=timezone.now().date() + timedelta(days=index*30),
                contrato=contrato
            )
                parcelamento.save()

        return render(
            request,
            "gestao/alugar_imovel.html",
            {
                "imovel": imovel,
                "preco_diaria": None if not preco_diaria else preco_diaria.valor,
                "preco_mensal": None if not preco_mensal else preco_mensal.valor
            }
        )

modulo03-python-web-com-django/20240427_aula10/gestao/templates/gestao/alugar_imovel.html
{% extends "base.html" %}

{% block conteudo %}
<h2 class="text-center">Alugar Imóvel</h2>
<hr>

<div class="row d-flex justify-content-center">
    <div class="col-6 text-center">
        <p class="fs-3">Confirmar o aluguel do imóvel {{ imovel }}</p>
    </div>
</div>

<form action="" id="form-alugar" method="POST">
    {% csrf_token %}
    <input type="hidden" name="imovel_id" value="{{ imovel.id }}">
    <div class="row d-flex justify-content-center" style="max-height: 40px;">
        <div class="col-3">
            <select class="form-select" name="tipo_contrato" id="tipo_contrato" aria-label="Seleção de contratos de aluguel">
                <option selected>Escolha o tipo de contrato</option>
                {% if preco_diaria %}
                    <option value="1">Diário</option>
                {% endif %}
                {% if preco_mensal %}
                    <option value="2">Mensal</option>                
                {% endif %}
              </select>
        </div>
        <div class="col-1 text-end">
            <label for="periodo" class="form-label">Período</label>
        </div>
        <div class="col-2">
                <input
                type="number"
                name="periodo"
                id="periodo"
                min="1"
                max="30"
                class="form-control"
                placeholder="1"
                >
        </div>
    </div>
    <div class="row d-flex justify-content-center mt-3">
        <div class="col-6">
            <div class="d-grid">
                <button type="submit" class="btn btn-primary">Alugar</button>
            </div>
        </div>
    </div>
</form>

{% endblock conteudo %}

modulo03-python-web-com-django/20240427_aula10/gestao/templates/gestao/detalhe_imovel.html
{% extends "base.html" %}

{% block conteudo %}
<h2 class="text-center">Detalhes do Imóvel</h2>
<hr>

<div class="row">
    <div class="col text-center">
        
        <p>
            <strong>Descrição: </strong>
            {{ imovel.descricao }}
        </p>
    </div>
    <div class="row">
        <div class="col text-center">
            <p>
                <strong>Endereço: </strong>
                {{ imovel.tipo_logradouro }} 
                {{ imovel.logradouro }}, 
                {{ imovel.numero }}, 
                {{ imovel.bairro }}, 
                {{ imovel.cidade }}, 
                {{ imovel.estado }}.
            </p>
        </div>
    </div>
    {% if preco_diaria %}
        <div class="row">
            <div class="col text-center">
                <p><strong>Preço do aluguel diário: </strong>R$ {{ preco_diaria|floatformat:2 }}</p>
            </div>
        </div>
    {% endif %}
    {% if preco_mensal %}
        <div class="row">
            <div class="col text-center">
                <p><strong>Preço do aluguel mensal: </strong>R$ {{ preco_mensal|floatformat:2 }}</p>
            </div>
        </div>
    {% endif %}
    <div class="row d-flex justify-content-center">
        <div class="col-4">
            <div class="d-grid">
                <a href="{% url 'gestao:alugar_imovel' imovel.id %}" class="btn btn-primary" tabindex="-1" role="button" aria-disabled="true">Alugar</a>
            </div>
        </div>
    </div>
</div>

{% endblock conteudo %}

modulo03-python-web-com-django/20240427_aula10/gestao/templates/gestao/index.html
{% extends "base.html" %}

{% block conteudo %}
    <div class="row">
        <div class="col text-center">
            {% if user.is_authenticated %}
                <p>Você está logado como {{ user.username }}.</p>
                <form action="{% url "logout" %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Logout</button>
                </form>
            {% else %}
                <p>Você não está logado. <a href="{% url "login" %}">Clique aqui</a> para ir para a página de login.</p>
            {% endif %}
        </div>
    </div>
{% endblock conteudo %}

modulo03-python-web-com-django/20240427_aula10/gestao/templates/gestao/lista_imoveis.html
{% extends "base.html" %}

{% block conteudo %}
    <h2 class='text-center'>Alugar Imóvel</h2>
    <hr>

    <div class="row row-cols-4">
        {% for imovel in imoveis %}
            <div class="col">
                <div class="card" style="width: 15rem">
                    <div class="card-body">
                        {% if imovel.preco_mensal %}
                            <h5 class="card-title">
                                Aluguel mensal: R$ {{ imovel.preco_mensal|floatformat:2 }}
                            </h5>
                        {% endif %}
                        {% if imovel.preco_diaria %}
                            <h6 class="card-subtitle">
                                Diária: R$ {{ imovel.preco_diaria|floatformat:2 }}
                            </h6>
                        {% endif %}
                      <p class="card-text">{{ imovel.descricao }}</p>
                      <a href="{% url 'gestao:detalhe_imovel' imovel.id %}" class="card-link">Ir para os detalhes</a>
                    </div>
                  </div>
            </div>
        {% endfor %}
    </div>

{% endblock conteudo %}

modulo03-python-web-com-django/20240427_aula10/gestao/templates/gestao/meu_perfil.html
{% extends "base.html" %}

{% block conteudo %}
    <div class="row">
        <div class="col text-center">
            <h3>Perfil de {{ user.first_name }} {{ user.last_name }}</h3>
        </div>
    </div>

    <hr>

    {% if atualizado_com_sucesso %}
        <div class="row lh-1 d-flex justify-content-center">
            <div class="col-6 text-center">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <p>Dados atualizados com sucesso!</p>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
    {% endif %}

    {% if erros %}
        <div class="row mt-2"></div>

        {% for erro in erros %}
            <div class="row lh-1 d-flex justify-content-center">
                <div class="col-6 text-center">
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <p>{{ erro }}</p>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>
            </div>
        
        {% endfor %}

    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-3">
                <div class="form-floating">
                    <input
                        type="text"
                        name="nome"
                        id="nome"
                        class="form-control"
                        placeholder="Nome"
                        value="{{ user.first_name }}"
                        required>
                    <label for="nome">Nome</label>
                </div>
            </div>
            <div class="col-3">
                <div class="form-floating">
                    <input
                        type="text"
                        name="sobrenome"
                        id="sobrenome"
                        class="form-control"
                        placeholder="Sobrenome"
                        value="{{ user.last_name }}"
                        required>
                    <label for="sobrenome">Sobrenome</label>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-2">
            <div class="col-6">
                <div class="form-floating">
                    <input
                        type="text"
                        name="email"
                        id="email"
                        class="form-control"
                        placeholder="E-mail"
                        value="{{ user.email }}"
                        required
                    >
                    <label for="email">E-mail</label>
                </div>
            </div>
        </div>
        <hr>
        <div class="row justify-content-center mt-2">
            <div class="col-2">
                <div class="form-floating">
                    <input
                        type="text"
                        name="documento"
                        id="documento"
                        class="form-control"
                        placeholder="Documento"
                        value="{{ user.perfil.documento|default:'' }}"
                        required
                    >
                    <label for="documento">Documento</label>
                </div>
            </div>
            <div class="col-2">
                <div class="form-floating">
                    <select name="genero" id="genero" class="form-select form-select-sm">
                        <option {% if user.perfil.genero %}{% else %}selected{% endif %}>Escolha o gênero</option>
                        <option {% if user.perfil.genero == 'm' %}selected{% endif %} value="m">Masculino</option>
                        <option {% if user.perfil.genero == 'f' %}selected{% endif %} value="f">Feminino</option>
                    </select>
                </div>
            </div>
            <div class="col-2">
                <div class="form-floating">
                    <input
                        type="date"
                        name="data_de_nascimento"
                        id="data_de_nascimento"
                        min="1900-01-01"
                        max="2003-12-31"
                        class="form-control"
                        value="{{ user.perfil.data_de_nascimento|date:'Y-m-d'}}"
                        required
                    >
                </div>
            </div>
        </div>

        <div class="row justify-content-center mt-3">
            <div class="col-3 d-grid">
                <button type="submit" class="btn btn-primary">Confirmar</button>
            </div>
        </div>
    </form>

{% endblock conteudo %}

modulo03-python-web-com-django/20240427_aula10/gestao/templates/gestao/nao_autorizado.html
{% extends "base.html" %}

{% block conteudo %}
    <div class="row">
        <div class="col text-center">
            <p>Você não tem autorização para acessar essa página. Entre em contato com o administrador. <a href="{% url 'gestao:index' %}">Clique aqui</a> para voltar a página principal.</p>
        </div>
    </div>
{% endblock conteudo %}